package pharmacy_stock_management_system;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        add_fill_table();
    }
    public void clearinputs(){
        id.setText("");
        username_txtfield.setText("");
        password_txtfield.setText("");
        post_txtfield.setText("");
        email_txtfield.setText("");
    }
    public void add_fill_table() {
    try {
        Connection Con2 = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "root", "Mych0ice@12345");
        DefaultTableModel model1 = (DefaultTableModel) users_tbl.getModel();
            
            model1.setRowCount(0);    
            Statement st=Con2.createStatement();
            ResultSet rs5 = st.executeQuery("SELECT * FROM login");
            ResultSetMetaData rsmd=(ResultSetMetaData) rs5.getMetaData();
            DefaultTableModel model =(DefaultTableModel) users_tbl.getModel();
            
            int cols = rsmd.getColumnCount();
            String[] colName = new String[cols];
            for(int i=0;    i<cols; i++){
                colName[i]=rsmd.getColumnName(i+1);
                model.setColumnIdentifiers(colName);
                String id,user_name,password,post,email;
                while(rs5.next()){
                    id = rs5.getString(1);
                    user_name = rs5.getString(2);
                    password = rs5.getString(3);
                    post = rs5.getString(4);
                    email = rs5.getString(5);

                    String[] row = {id,user_name,password,post,email};
                    model.addRow(row);
                }
                
            }

        st.close();
        Con2.close();

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new app.bolivia.swing.JCTextField();
        username_txtfield = new app.bolivia.swing.JCTextField();
        password_txtfield = new app.bolivia.swing.JCTextField();
        post_txtfield = new app.bolivia.swing.JCTextField();
        email_txtfield = new app.bolivia.swing.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        users_tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        add_user = new rojerusan.RSMaterialButtonCircle();
        delete_user = new rojerusan.RSMaterialButtonCircle();
        search_user = new rojerusan.RSMaterialButtonCircle();
        jButton1 = new javax.swing.JButton();
        update_btn = new rojerusan.RSMaterialButtonCircle();
        generate_pass_btn = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        password_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_txtfieldActionPerformed(evt);
            }
        });

        post_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                post_txtfieldActionPerformed(evt);
            }
        });

        email_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtfieldActionPerformed(evt);
            }
        });

        users_tbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        users_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "users"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(users_tbl);
        if (users_tbl.getColumnModel().getColumnCount() > 0) {
            users_tbl.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel1.setBackground(new java.awt.Color(40, 96, 148));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sno");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(40, 96, 148));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("user name");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(40, 96, 148));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("password");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(40, 96, 148));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("email");
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(40, 96, 148));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("post");
        jLabel5.setOpaque(true);

        add_user.setBackground(new java.awt.Color(40, 96, 148));
        add_user.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_user.setText("Add");
        add_user.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_userActionPerformed(evt);
            }
        });

        delete_user.setBackground(new java.awt.Color(40, 96, 148));
        delete_user.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete_user.setText("Delete");
        delete_user.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        delete_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_userActionPerformed(evt);
            }
        });

        search_user.setBackground(new java.awt.Color(40, 96, 148));
        search_user.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_user.setText("search");
        search_user.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        search_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_userActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(40, 96, 148));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        update_btn.setBackground(new java.awt.Color(40, 96, 148));
        update_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_btn.setText("update");
        update_btn.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        generate_pass_btn.setBackground(new java.awt.Color(40, 96, 148));
        generate_pass_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generate_pass_btn.setText("generate");
        generate_pass_btn.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        generate_pass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_pass_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(108, 108, 108)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add_user, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username_txtfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(post_txtfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(email_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(search_user, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(password_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generate_pass_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(delete_user, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_user, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username_txtfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generate_pass_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(post_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_user, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_user, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void password_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_txtfieldActionPerformed

    private void post_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_post_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_post_txtfieldActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_userActionPerformed
        // TODO add your handling code here:
        if(id.getText().equals("") || post_txtfield.getText().equals("")||password_txtfield.getText().equals("") ) {
        JOptionPane.showMessageDialog(this, "Please fill in all textboxes.");
    }
        else {
        try {
             Connection Con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "root", "Mych0ice@12345");
            PreparedStatement add = Con.prepareStatement("INSERT INTO login (sno,username,password,post) VALUES (?, ?, ?, ?)");
            add.setInt(1, Integer.parseInt(id.getText()));
            add.setString(2, id.getText());
            add.setString(3, password_txtfield.getText());
            add.setString(4, post_txtfield.getText());
            //add.setString(5,email_txtfield.getText());
            
          
            add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data added successfully");
            clearinputs();
            add_fill_table();
           
            Con.close();
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage());
            
        }
    }
    }//GEN-LAST:event_add_userActionPerformed

    private void delete_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_userActionPerformed
        // TODO add your handling code here:
        try {
            Connection Con1 = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "root", "Mych0ice@12345");
            PreparedStatement del = Con1.prepareStatement("DELETE FROM login WHERE sno=?");
            del.setInt(1, Integer.parseInt(id.getText()));
            JOptionPane.showMessageDialog(this, "Data deleted successfully");
        
            del.executeUpdate();
            
        Con1.close();
        clearinputs();
        add_fill_table();
          

        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage());
        }
        
    }//GEN-LAST:event_delete_userActionPerformed

    private void search_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_userActionPerformed
        // TODO add your handling code here:
        try {
            Connection Con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "root", "Mych0ice@12345");
            String sql = "SELECT * FROM login WHERE sno = ?";
    
            // Create a PreparedStatement
            try (PreparedStatement statement = Con.prepareStatement(sql)) {
        
        
                
                int Id = Integer.parseInt(id.getText());
                statement.setInt(1, Id);
        
                // Execute the query
                ResultSet resultSet = statement.executeQuery();
        
                // Check if any results were returned
                if (resultSet.next()) {
                    // Set the values in your text fields based on the retrieved data
                    username_txtfield.setText(resultSet.getString("username"));
                    password_txtfield.setText(resultSet.getString("password"));
                    post_txtfield.setText(resultSet.getString("post"));
                    email_txtfield.setText(resultSet.getString("email"));
                    
                    
                    
            
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No data found for the specified med_id.");
                    clearinputs();
                }
            }
    
            // Close the connection
            Con.close();
        }
        catch (SQLException | NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        finally
        {
            menu.DatabaseManager.closeConnection();
        }
        
    }//GEN-LAST:event_search_userActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
       
        
        try {
    Connection Con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "root", "Mych0ice@12345");

    // Update query without modifying the ID
    String query = "UPDATE login SET username=?, password=?, post=?, email=? WHERE sno=?";
    
    PreparedStatement pst = Con.prepareStatement(query);

    pst.setString(1, username_txtfield.getText());
    pst.setString(2, password_txtfield.getText());
    pst.setString(3, post_txtfield.getText());
    pst.setString(4, email_txtfield.getText());
    
    // Set the ID in the WHERE clause
    pst.setInt(5, Integer.parseInt(id.getText()));
    
    
    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Data updated successfully");

    // Clear input fields
    clearinputs();
    add_fill_table();

} catch (SQLException | HeadlessException | NumberFormatException e) {
    JOptionPane.showMessageDialog(null, e);
}

        
        
        
    }//GEN-LAST:event_update_btnActionPerformed

    private void email_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtfieldActionPerformed

    private void generate_pass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_pass_btnActionPerformed
        // TODO add your handling code here:
       
        String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*?";
        int length = 10; // Adjust password length as needed
        Random random = new Random();
        StringBuilder passwordBuilder = new StringBuilder();
        for (int i = 0; i < length; i++) {
            passwordBuilder.append(characters.charAt(random.nextInt(characters.length())));
        }
        password_txtfield.setText(passwordBuilder.toString());
    }//GEN-LAST:event_generate_pass_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle add_user;
    private rojerusan.RSMaterialButtonCircle delete_user;
    private app.bolivia.swing.JCTextField email_txtfield;
    private rojerusan.RSMaterialButtonCircle generate_pass_btn;
    private app.bolivia.swing.JCTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private app.bolivia.swing.JCTextField password_txtfield;
    private app.bolivia.swing.JCTextField post_txtfield;
    private rojerusan.RSMaterialButtonCircle search_user;
    private rojerusan.RSMaterialButtonCircle update_btn;
    private app.bolivia.swing.JCTextField username_txtfield;
    private javax.swing.JTable users_tbl;
    // End of variables declaration//GEN-END:variables
}
